/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "OscillatorEditor.h"


//==============================================================================
/**
*/
class ArtifaktAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    ArtifaktAudioProcessorEditor (ArtifaktAudioProcessor&);
    ~ArtifaktAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    ArtifaktAudioProcessor& processor;
    
    OscillatorEditor m_topOscillatorEditor;
    OscillatorEditor m_bottomOscillatorEditor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (ArtifaktAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
